# Fill these on Streamlit Cloud (or locally for testing)
ADMIN_USER = "admin"
# SHA256 of your password (example only; replace this hash)
ADMIN_PASSWORD_HASH = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"  # 'admin' (example)
APP_SECRET = "change_this_to_a_long_random_secret"
